version: '2'
services:
  ingest:
    build: ingest
    ports:
    - "5000:5000"
    volumes:
    - .:/code
    - logvolume01:/var/log
    links:
    - SOLR1

  webapp:
    build: webapp
    ports:
    - "3000:3000"
    
  facedetect:
    build: facedetect
    ports:
    - "8888:8888"
    
  SOLR1:
    image: solr
    hostname: solr1
    ports:
      - "8983:8983"

volumes:
  logvolume01: {}

